## Nonlinear Model Predictive Control Params
controller/NMPC: 
# Optimization Setup
  dt: 0.1 #s
  N:  15

  # Weight Matrices
  Q_x:      1.0
  Q_y:      1.0
  Q_theta:  1.0 

  R_v:      1.0
  R_omega:  1.0

  # Boundary Action Control
  v_max:      0.8 # m/s
  omega_max:  1.5 # rad/s

## Odometry Params
odom:
  frame_id: "/terrasentia/will/odom"
