## Nonlinear Model Predictive Control Params
controller/NMPC: 
# Optimization Setup
  dt: 0.1 #s
  N:  15

  # Weight Matrices
  Q_x:      5.0
  Q_y:      5.0
  Q_theta:  3.5 

  R_v:      0.5
  R_omega:  0.1

  # Boundary Action Control
  v_max:      1.2 # m/s
  omega_max:  2.0 # rad/s

## Odometry Params
odom:
  frame_id: "/terrasentia/will/odom"