## Nonlinear Model Predictive Control Params
controller/NMPC: 
# Optimization Setup
  dt: 0.1 #s
  N:  10

  # Weight Matrices
  Q_x:      7.5
  Q_y:      7.5
  Q_theta:  1.0 

  R_v:      0.75
  R_omega:  0.1

  # Boundary Action Control
  v_max:      1.0 # m/s
  omega_max:  1.0 # rad/s

