wp_gen/img:
  row_height: 7.5   # [m]
  row_width: 1.35   # [m]
  img_height: 244   # [px]
  img_width: 244    # [px]
  D: 1.5            # Waypoint Distance [m]

wp_gen/odom:
  topic: "/terrasentia/will/odom"
  frame_id: "terrasentia/will/odom"

