wp_gen/img:
  row_height: 3.5   # [m]
  row_width: 4.0    # [m]
  img_height: 244   # [px]
  img_width: 244    # [px]
  D: 1.3            # Waypoint Distance [m]

wp_gen/odom:
  topic: "/terrasentia/will/odom"
  frame_id: "terrasentia/will/odom"

