## iterative Linear Quatratic Regulator

controller/iLQR:
  N:    &N  15
  dt:   &dt 0.1
  v_max: 1.2
  omega_max: 2.0

controller/cost: 
  N: *N
  
  # Weight Matrices
  Qf_x:     5.0
  Qf_y:     5.0
  Qf_theta: 3.5

  Q_x:      3.0
  Q_y:      3.0
  Q_theta:  1.0

  R_v:      0.75
  R_omega:  0.5

controller/dynamics:
  dt: *dt
  model: "standard"

## Odometry Params
odom:
  frame_id: "/terrasentia/will/odom"