## iterative Linear Quatratic Regulator

controller/iLQR:
  # Prediction Params
  N:    &N  15
  dt:   &dt 0.1

  # Optimization Params
  shoot_fac:  0.8     # Exponential factor (exp(fac*x))
  max_iter:   50     # Max iterations of fit function
  tol:        0.01    # Min tolerance for convergence

controller/cost: 
  N: *N
  
  # Weight Matrices
  Qf_x:     1.0
  Qf_y:     1.0
  Qf_theta: 2.5

  Q_x:      5.0
  Q_y:      5.0
  Q_theta:  1.0

  R_v:      0.01
  R_omega:  0.01

  v_max:      1.0
  omega_max:  1.0

  eps: 10000
  t: 1

controller/dynamics:
  dt: *dt
  model: "standard"

## Odometry Params
odom:
  topic: "/terrasentia/will/odom"
  frame_id: "/terrasentia/will/odom"